//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastingStars.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CastingStars.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Nav {
            get {
                return ResourceManager.GetString("About_Nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact_Nav {
            get {
                return ResourceManager.GetString("Contact_Nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew.
        /// </summary>
        public static string Crew_Nav {
            get {
                return ResourceManager.GetString("Crew_Nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET.
        /// </summary>
        public static string Forgot_Button {
            get {
                return ResourceManager.GetString("Forgot_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crew.
        /// </summary>
        public static string Home_Crew {
            get {
                return ResourceManager.GetString("Home_Crew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to our featured.
        /// </summary>
        public static string Home_Featured {
            get {
                return ResourceManager.GetString("Home_Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locations.
        /// </summary>
        public static string Home_Locations {
            get {
                return ResourceManager.GetString("Home_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more crew.
        /// </summary>
        public static string Home_More_Crew {
            get {
                return ResourceManager.GetString("Home_More_Crew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more locations.
        /// </summary>
        public static string Home_More_Locations {
            get {
                return ResourceManager.GetString("Home_More_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more talents.
        /// </summary>
        public static string Home_More_Talents {
            get {
                return ResourceManager.GetString("Home_More_Talents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Nav {
            get {
                return ResourceManager.GetString("Home_Nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find star.
        /// </summary>
        public static string Home_Search_Button {
            get {
                return ResourceManager.GetString("Home_Search_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanted: actors, models, musicians, and more.
        /// </summary>
        public static string Home_Search_Text_1 {
            get {
                return ResourceManager.GetString("Home_Search_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60, 378.
        /// </summary>
        public static string Home_Search_Text_2 {
            get {
                return ResourceManager.GetString("Home_Search_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roles for all ages, looks &amp; levels of experience.
        /// </summary>
        public static string Home_Search_Text_3 {
            get {
                return ResourceManager.GetString("Home_Search_Text_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to talents.
        /// </summary>
        public static string Home_Talents {
            get {
                return ResourceManager.GetString("Home_Talents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the first.
        /// </summary>
        public static string Home_Text_1 {
            get {
                return ResourceManager.GetString("Home_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to casting portal.
        /// </summary>
        public static string Home_Text_2 {
            get {
                return ResourceManager.GetString("Home_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the middle east.
        /// </summary>
        public static string Home_Text_3 {
            get {
                return ResourceManager.GetString("Home_Text_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Home_User_Login_1 {
            get {
                return ResourceManager.GetString("Home_User_Login_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to your dashboard.
        /// </summary>
        public static string Home_User_Login_2 {
            get {
                return ResourceManager.GetString("Home_User_Login_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Now.
        /// </summary>
        public static string Home_User_Register {
            get {
                return ResourceManager.GetString("Home_User_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who&apos;s next?.
        /// </summary>
        public static string Home_User_Text {
            get {
                return ResourceManager.GetString("Home_User_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Locations_Nav {
            get {
                return ResourceManager.GetString("Locations_Nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Login_Forgot_pass {
            get {
                return ResourceManager.GetString("Login_Forgot_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Now.
        /// </summary>
        public static string Login_Register {
            get {
                return ResourceManager.GetString("Login_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string Login_Remember {
            get {
                return ResourceManager.GetString("Login_Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout_User {
            get {
                return ResourceManager.GetString("Logout_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200,000 users registered since January.
        /// </summary>
        public static string Lower_Footer_Text_1 {
            get {
                return ResourceManager.GetString("Lower_Footer_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we have created the product that will help you startup to look even better.
        /// </summary>
        public static string Lower_Footer_Text_2 {
            get {
                return ResourceManager.GetString("Lower_Footer_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string Membership_Nav {
            get {
                return ResourceManager.GetString("Membership_Nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My List.
        /// </summary>
        public static string My_List_User {
            get {
                return ResourceManager.GetString("My_List_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Privacy_Policy {
            get {
                return ResourceManager.GetString("Privacy_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Profile.
        /// </summary>
        public static string Profile_Agency_Link {
            get {
                return ResourceManager.GetString("Profile_Agency_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Player.
        /// </summary>
        public static string Profile_Audio {
            get {
                return ResourceManager.GetString("Profile_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew Profile.
        /// </summary>
        public static string Profile_Crew_Link {
            get {
                return ResourceManager.GetString("Profile_Crew_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile Picture.
        /// </summary>
        public static string Profile_Edit_Picture {
            get {
                return ResourceManager.GetString("Profile_Edit_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Profile_Form_Message {
            get {
                return ResourceManager.GetString("Profile_Form_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Profile_Form_Name {
            get {
                return ResourceManager.GetString("Profile_Form_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Profile_Form_Password {
            get {
                return ResourceManager.GetString("Profile_Form_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Profile_Form_Surname {
            get {
                return ResourceManager.GetString("Profile_Form_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASIC FORM.
        /// </summary>
        public static string Profile_Form_Title {
            get {
                return ResourceManager.GetString("Profile_Form_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Profile.
        /// </summary>
        public static string Profile_Location_Link {
            get {
                return ResourceManager.GetString("Profile_Location_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Work (Portfolio).
        /// </summary>
        public static string Profile_Pastwork {
            get {
                return ResourceManager.GetString("Profile_Pastwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string Profile_Personal_Information {
            get {
                return ResourceManager.GetString("Profile_Personal_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Gallery.
        /// </summary>
        public static string Profile_Photo {
            get {
                return ResourceManager.GetString("Profile_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Information.
        /// </summary>
        public static string Profile_Professional_Information {
            get {
                return ResourceManager.GetString("Profile_Professional_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Type.
        /// </summary>
        public static string Profile_Professional_Type {
            get {
                return ResourceManager.GetString("Profile_Professional_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Progress.
        /// </summary>
        public static string Profile_Progress {
            get {
                return ResourceManager.GetString("Profile_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talent Profile.
        /// </summary>
        public static string Profile_Talent_Link {
            get {
                return ResourceManager.GetString("Profile_Talent_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Profile_Upload {
            get {
                return ResourceManager.GetString("Profile_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Reel.
        /// </summary>
        public static string Profile_Video {
            get {
                return ResourceManager.GetString("Profile_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Message.
        /// </summary>
        public static string Profile_Warning {
            get {
                return ResourceManager.GetString("Profile_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        public static string Register_Button {
            get {
                return ResourceManager.GetString("Register_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Register_Confirm {
            get {
                return ResourceManager.GetString("Register_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Register_Email {
            get {
                return ResourceManager.GetString("Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Terms.
        /// </summary>
        public static string Special_Terms {
            get {
                return ResourceManager.GetString("Special_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talents.
        /// </summary>
        public static string Talents_Nav {
            get {
                return ResourceManager.GetString("Talents_Nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string Terms_Of_Service {
            get {
                return ResourceManager.GetString("Terms_Of_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we are mobile!.
        /// </summary>
        public static string Upper_Footer_Text_1 {
            get {
                return ResourceManager.GetString("Upper_Footer_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never miss a chance.
        /// </summary>
        public static string Upper_Footer_Text_2 {
            get {
                return ResourceManager.GetString("Upper_Footer_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to be the next star!.
        /// </summary>
        public static string Upper_Footer_Text_3 {
            get {
                return ResourceManager.GetString("Upper_Footer_Text_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Over.
        /// </summary>
        public static string Voice_Nav {
            get {
                return ResourceManager.GetString("Voice_Nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome_User {
            get {
                return ResourceManager.GetString("Welcome_User", resourceCulture);
            }
        }
    }
}
